--- #YAML:1.0
name:                Music-Tag-Lyrics
version:             0.29
abstract:            Screen Scraping plugin for downloading lyrics from the web.  
license:             perl
author:              
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cache::Cache:                  1.05
    Encode:                        2.12
    File::Spec:                    3.24
    IO::File:                      1.13
    LWP:                           5.805
    Music::Tag:                    0.27
    Test::More:                    0
    URI::Escape:                   3.28
    URI::WithBase:                 2.19
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
